"""Rasterize original Lucide SVGs into 4-bit coverage at 24 and 32 px."""
from pathlib import Path
from io import BytesIO
import ctypes.util
# Resolve Homebrew explicitly when running under a bundled macOS Python.
_find_library=ctypes.util.find_library
def _resolve(name):
 return "/opt/homebrew/lib/libcairo.2.dylib" if name in ("cairo","cairo-2") and Path("/opt/homebrew/lib/libcairo.2.dylib").exists() else _find_library(name)
ctypes.util.find_library=_resolve
import cairosvg
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
names=['bluetooth','plug','battery','battery-low','battery-medium','battery-full','battery-charging','battery-warning']
out=['// Generated by scripts/build_device_icons.py. Lucide ISC license.\n#pragma once\n#include <stdint.h>\n']
for size in (24,32):
 for name in names:
  source=(ROOT/f'crew-app/ui/art/icons/lucide-{name}.svg').read_text().replace('currentColor','#fff')
  raw=cairosvg.svg2png(bytestring=source.encode(),output_width=size,output_height=size)
  alpha=Image.open(BytesIO(raw)).convert('RGBA').getchannel('A')
  levels=[(v+8)//17 for v in alpha.get_flattened_data()]
  packed=[(levels[i]<<4)|levels[i+1] for i in range(0,len(levels),2)]
  out.append(f'inline constexpr uint8_t icon_{name.replace("-","_")}_{size}[]={{'+','.join(map(str,packed))+'};\n')
(ROOT/'firmware/src/lucide_icons.h').write_text(''.join(out))
