"""Bake Space Grotesk into four 4-bit coverage atlases (Pillow 12.3.0).
Run with Python + Pillow; no font conversion or filesystem access on the device.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
ROOT=Path(__file__).resolve().parents[1]
CHARS=list(range(32,127))+[0x2026]

def build():
    output=['// Generated by scripts/build_fonts.py; Space Grotesk, SIL OFL 1.1.\n#pragma once\n#include <stdint.h>\nstruct SmoothGlyph {uint32_t offset; uint8_t width,height,advance; int8_t left,top;};\nstruct SmoothFont {const uint8_t* pixels; const SmoothGlyph* glyphs; uint8_t baseline;};\n']
    for size,weight in ((20,'Regular'),(24,'Regular'),(36,'Bold'),(48,'Bold'),(64,'Bold'),(80,'Bold'),(120,'Bold')):
        font=ImageFont.truetype(str(ROOT/f'firmware/assets/fonts/SpaceGrotesk-{weight}.ttf'),size,layout_engine=ImageFont.Layout.BASIC)
        data=[];glyphs=[]
        for cp in CHARS:
            ch=chr(cp);l,t,r,b=font.getbbox(ch,anchor='ls');w=r-l;h=b-t
            im=Image.new('L',(max(1,w),max(1,h)))
            ImageDraw.Draw(im).text((-l,-t),ch,font=font,fill=255,anchor='ls')
            levels=[(v+8)//17 for v in im.get_flattened_data()] if w*h else []
            glyphs.append((len(data),w,h,round(font.getlength(ch)),l,t))
            if len(levels)%2:levels.append(0)
            data.extend((levels[i]<<4)|levels[i+1] for i in range(0,len(levels),2))
        output.append(f'inline constexpr uint8_t space{size}Pixels[] = {{\n'+','.join(map(str,data))+'};\n')
        output.append(f'inline constexpr SmoothGlyph space{size}Glyphs[] = {{\n'+',\n'.join('{'+','.join(map(str,g))+'}' for g in glyphs)+'};\n')
        output.append(f'inline constexpr SmoothFont space{size} = {{space{size}Pixels,space{size}Glyphs,{round(size*.75)}}};\n')
        print(f'{size}px {weight}: {len(data)} bytes')
    (ROOT/'firmware/src/fonts/space_grotesk.h').write_text(''.join(output))
if __name__=='__main__':build()
