"""Generate Crew external-image fallbacks and inline markup from one duotone SVG.
Palette and host sizes verified against Kiro Crew's shipped AppIcon and AppTile.
Built-ins inherit --ico-a/--ico-b; external <img> SVGs cannot inherit host CSS.
"""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'crew-app/ui/art'

def build():
    source = (ART / 'icon-crew.svg').read_text()
    # AppTile: 30px SVG inside 58px tile; detail: 64px inside 96px.
    # External images fill those tiles, so reproduce the built-in inset only
    # at tile sizes. Sidebar/inline instances keep the full 24-unit viewBox.
    sizing = '''<style>
.kirometer-mark { transform-origin:12px 12px; }
@media (min-width:48px) and (max-width:79px) { .kirometer-mark { transform:scale(0.5172413793); } }
@media (min-width:80px) { .kirometer-mark { transform:scale(0.6666666667); } }
</style>'''
    for theme, neutral in [('light', '#5e5966'), ('dark', '#938f9b')]:
        svg = source.replace('var(--ico-a, currentColor)', neutral).replace('var(--ico-b, currentColor)', '#8e48ff')
        svg = svg.replace('<g class="kirometer-mark">', sizing + '\n  <g class="kirometer-mark">')
        (ART / f'icon-crew-{theme}.svg').write_text(svg)
    (ROOT / 'crew-app/ui/app-icon.mjs').write_text('// Generated by scripts/build_app_icon.py; edit art/icon-crew.svg.\nexport const deviceIconSvg = ' + json.dumps(source) + ';\n')

if __name__ == '__main__':
    build()
