"""Convert licensed Spirit of Kiro poses into opaque RGB565 on pure black.
West is mirrored East: the upstream asset folder does not contain west.png.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageOps
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'previews/assets/kiro-ghost'
EYES={'south':[(1066,753,1203,975),(1306,753,1443,975)],
      'east':[(1325,732,1462,953),(1565,732,1703,953)],'north':[]}
arrays=[]
atlas=Image.new('RGB',(123*4,150*2))
for index,direction in enumerate(('south','east','north','west')):
    original='east' if direction=='west' else direction
    im=Image.open(SOURCE/f'{original}.png').convert('RGBA')
    box=im.getbbox()
    for closed in (False,True):
        frame=im.copy()
        if closed:
            pen=ImageDraw.Draw(frame)
            for x1,y1,x2,y2 in EYES[original]:
                pen.rectangle((x1-3,y1-3,x2+3,y2+3),fill='white')
                mid=(y1+y2)//2
                pen.rounded_rectangle((x1,mid-10,x2,mid+10),radius=10,fill='black')
        frame=frame.crop(box)
        if direction=='west':frame=ImageOps.mirror(frame)
        frame.thumbnail((123,150),Image.Resampling.LANCZOS)
        canvas=Image.new('RGB',(123,150),'black')
        canvas.paste(frame,((123-frame.width)//2,(150-frame.height)//2),frame)
        pixels=[]
        for r,g,b in canvas.getdata():pixels.append(((r>>3)<<11)|((g>>2)<<5)|(b>>3))
        name=f'GHOST_{direction.upper()}'+('_BLINK' if closed else '')
        arrays.append('static const uint16_t '+name+'[] PROGMEM={\n'+ '\n'.join(','.join(f'0x{v:04x}' for v in pixels[i:i+24])+',' for i in range(0,len(pixels),24))+'\n};\n')
        atlas.paste(canvas,(index*123,int(closed)*150))
(ROOT/'firmware/src/ghost_poses.h').write_text('#pragma once\n#include <Arduino.h>\n// Generated by scripts/build_ghost_sprites.py; see firmware/GHOST-LICENSE.\n'+''.join(arrays))
atlas.save(ROOT/'previews/assets/kiro-ghost/firmware-atlas.png')

# Export the same C++ motion used on-device for the browser preview.
import subprocess
import tempfile
with tempfile.TemporaryDirectory() as tmp:
    binary=Path(tmp)/'ghost-motion'
    subprocess.run(['c++','-std=c++17',str(ROOT/'tests/export_ghost_motion.cpp'),'-o',str(binary)],check=True)
    (ROOT/'previews/assets/ghost-motion.json').write_bytes(subprocess.check_output([str(binary)]))
