"""Embed the firmware RGB565 sprites for offline gallery animation."""
from pathlib import Path
import re,struct,zlib,base64,json
root=Path(__file__).resolve().parents[1]
def png(values):
    raw=bytearray()
    for y in range(150):
        raw.append(0)
        for v in values[y*123:(y+1)*123]:
            raw.extend((round(((v>>11)&31)*255/31),round(((v>>5)&63)*255/63),round((v&31)*255/31),0 if v in (0,0x20e4) else 255))
    def chunk(t,d):return struct.pack('>I',len(d))+t+d+struct.pack('>I',zlib.crc32(t+d))
    return 'data:image/png;base64,'+base64.b64encode(b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',123,150,8,6,0,0,0))+chunk(b'IDAT',zlib.compress(raw))+chunk(b'IEND',b'')).decode()
assets={}
for filename in ['ghost_poses.h','ghost.h']:
    text=(root/'firmware/src'/filename).read_text()
    for name,body in re.findall(r'uint16_t (GHOST\w*)\[\] PROGMEM=\{(.*?)\};',text,re.S):
        values=[int(v,16) for v in re.findall(r'0x[0-9a-fA-F]+',body)]
        assert len(values)==123*150
        assets[name]=png(values)
        if name=='GHOST':
            for y in range(39,69):
                for x in list(range(59,77))+list(range(85,103)):values[y*123+x]=0x20e4 if 52<=y<55 else 0xffff
            assets['GHOST_BLINK']=png(values)
(root/'crew-app/ui/animation-assets.mjs').write_text('// Generated by scripts/build_animation_assets.py from firmware sprites.\nexport const sprites='+json.dumps(assets)+';\n')
